#listener configurations

listener.http.host=0.0.0.0
listener.http.port=8081
listener.http.path=/flights

#flights api Request configurations

flights.api.host=training4-american-ws.cloudhub.io
flights.api.port=80
flights.api.path=/api/flights